name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: false
        default: ''
permissions:
  contents: write
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Prepare version
        id: prepare-version
        run: |
          if test -z "${{github.event.inputs.version}}"
          then
          mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false
          else
          mvn versions:set -DnewVersion=${{github.event.inputs.version}} -DgenerateBackupPoms=false
          fi          
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
          echo "semantic-version=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`"
      - name: Commit version
        if: steps.prepare-version.outputs.changed == 'true'
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git commit -am "Prepare release version"
          git push
  echo-version:
    runs-on: ubuntu-latest
    needs: prepare-release
    steps:
      - name: echo man
        run: |
          echo "The version is ${{steps.prepare-release.outputs.semantic-version }}"
