name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: false
        default: ''
permissions:
  contents: write
jobs:
  prepare-release:
    name: Create Semantic Version
    uses: ./.github/actions/java-prepare-release.yml@main
    with:
      initial-version: ${{github.event.inputs.version}}
    secrets: inherit
  echo-version:
    runs-on: ubuntu-latest
    needs: prepare-release
    steps:
      - name: echo man
        run: |
          echo "The version is ${{needs.prepare-release.outputs.semantic-version }}"
