name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: false
        default: ''
permissions:
  contents: write
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Prepare version
        id: prepare-version
        run: |
          mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit version
        if: steps.prepare-version.outputs.changed == 'true'
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git commit -am "Prepare release version"
          git push