name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: false
        default: ''
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Prepare version
        run: |
          mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false 
          mvn versions:commit
#      - name: Commit report
#        run: |
#          git config --global user.name 'Your Name'
#          git config --global user.email 'your-username@users.noreply.github.com'
#          git commit -am "Automated report"
#          git push