name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      semantic-version:
        description: 'Version to release'
        required: false
        default: ''
      is-release-build:
        description: 'Is this a release build? (Ignored if semantic-version is provided)'
        type: boolean
        required: false
        default: false
permissions:
  contents: write
jobs:
  prepare-release:
    name: Prepare Version
    uses: ./.github/workflows/java-maven-prepare-release.yml
    with:
      semantic-version: ${{github.event.inputs.release-version}}
      is-release-build: true
    secrets: inherit
  echo-version:
    runs-on: ubuntu-latest
    needs: prepare-release
    steps:
      - name: echo man
        run: |
          echo "The version is ${{needs.prepare-release.outputs.semantic-version }}"
          echo "Is this a release build? ${{needs.prepare-release.outputs.is-release-build}}"
#  prepare-next-snapshot:
#    name: Prepare Next Snapshot Version
#    needs:
#      - prepare-release
#      - echo-version
#    uses: ./.github/workflows/java-prepare-next-snapshot.yml
#    secrets: inherit
