name: (Java Reusable Workflow) - Reset Version

# -----------------------------------------------------------------------------------
# This is a reusable workflow that can be used to explicitly set the version of a
# Maven-based Java project. The version will be set for all modules in the project
# -----------------------------------------------------------------------------------

on:
  workflow_call:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: ''

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Prepare version
        id: prepare-version
        run: |
          mvn versions:set -DnewVersion=${{inputs.version}} -DgenerateBackupPoms=false
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git commit -am "Prepare release version"
          git push
