name: (Java Reusable Workflow) - Prepare Release

# -----------------------------------------------------------------------------------
# This is a reusable workflow that can be used to adjust the version of a Maven-based
# Java project. The version will be set for all modules in the project and can either
# be explicitly set or, if no version is provided, the current version will be used.
# If the current version is a snapshot version, the snapshot suffix will be removed.
# -----------------------------------------------------------------------------------

on:
  workflow_call:
    inputs:
      release-version:
        description: 'Version to release'
        required: false
        type: string
        default: ''
    outputs:
      semantic-version:
        description: 'The semantic version derived/used for the release'
        value: ${{ jobs.prepare-release.outputs.semantic-version }}

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      semantic-version: ${{ steps.prepare-version.outputs.semantic-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Prepare version
        id: prepare-version
        run: |
          if test -z "${{inputs.release-version}}"
          then
          mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false
          else
          mvn versions:set -DnewVersion=${{inputs.release-version}} -DgenerateBackupPoms=false
          fi          
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
          echo "semantic-version=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_OUTPUT
      - name: Commit version
        if: steps.prepare-version.outputs.changed == 'true'
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git commit -am "Prepare release version"
          git push
